// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://naxgkgduoktwtobsgzsq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5heGdrZ2R1b2t0d3RvYnNnenNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MjQ5MjQsImV4cCI6MjA2ODUwMDkyNH0.NRQQQb9hQB-3wPbUppmd6lvMUGlBpclDsWaiCGvFFnQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});